options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - boardos-vm-b
      - --zone=asia-south1-c
      - --project=$PROJECT_ID
      - --tunnel-through-iap
      - --command=cd /home/adnankhan/boardos && git pull && docker compose build --no-cache frontend && docker compose up -d frontend
