options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/boardos-backend:$COMMIT_SHA', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
      '--build-arg', 'API_INTERNAL_URL=http://backend:3001',
      '-t', 'gcr.io/$PROJECT_ID/boardos-frontend:$COMMIT_SHA',
      './frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/boardos-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/boardos-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - boardos-vm
      - --zone=asia-south1-a
      - --project=$PROJECT_ID
      - --tunnel-through-iap
      - --command=cd /home/adnankhan/boardos && git pull && docker compose up -d --force-recreate
