-- Add REQUESTED_VIDEO and REQUESTED_PHONE to AttendanceMode enum
ALTER TYPE "AttendanceMode" ADD VALUE IF NOT EXISTS 'REQUESTED_VIDEO';
ALTER TYPE "AttendanceMode" ADD VALUE IF NOT EXISTS 'REQUESTED_PHONE';
