// app/terms/page.tsx
export const metadata = {
  title: 'Terms of Service — SafeMinutes',
  description: 'Terms governing your use of the SafeMinutes platform.',
};

function CastleLogo({ size = 22, color = '#C4973A' }: { size?: number; color?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 28 28" fill="none">
      <rect x="2"  y="2" width="4" height="4" rx="0.5" fill={color}/>
      <rect x="8"  y="2" width="4" height="4" rx="0.5" fill={color}/>
      <rect x="14" y="2" width="4" height="4" rx="0.5" fill={color}/>
      <rect x="20" y="2" width="4" height="4" rx="0.5" fill={color}/>
      <rect x="2" y="6" width="22" height="2" fill={color}/>
      <rect x="2" y="8" width="22" height="16" fill="none" stroke={color} strokeWidth="2"/>
      <path d="M10 24 L10 18 Q14 13.5 18 18 L18 24" stroke={color} strokeWidth="1.5" fill="none"/>
      <rect x="5"  y="12" width="4" height="4" stroke={color} strokeWidth="1.2" fill="none"/>
      <rect x="17" y="12" width="4" height="4" stroke={color} strokeWidth="1.2" fill="none"/>
    </svg>
  );
}

const sections = [
  {
    title: 'About the service',
    body: `SafeMinutes is a board governance platform for Indian private companies, operated by Passhai Technologies Private Limited ("we", "us", "our"). The platform helps companies manage board meetings, record resolutions, collect director votes, generate statutory minutes, and store governance documents.

By creating an account, you agree to these Terms of Service. If you are using SafeMinutes on behalf of a company, you represent that you have authority to bind that company to these terms.`,
  },
  {
    title: 'Your account',
    body: `You are responsible for maintaining the security of your account credentials. Do not share your password. If you suspect unauthorised access to your account, notify us immediately at hello@safeminutes.com.

You must provide accurate information when creating your account. Accounts created with false information may be suspended. You must be at least 18 years old to use SafeMinutes.

Each account is for one natural person. You may not share your account with others. Company workspaces support multiple users — invite colleagues as directors or Company Secretaries rather than sharing credentials.`,
  },
  {
    title: 'Your data',
    body: `You own all data you create in SafeMinutes — meeting records, resolutions, votes, minutes, uploaded documents. We do not claim any rights over your content.

You grant us a limited licence to process, store, and display your data for the purpose of providing the service. This licence ends when you delete your account or company workspace, subject to the statutory retention requirements described in our Privacy Policy.

You are responsible for ensuring that the data you enter into SafeMinutes is accurate and that you have authority to enter it. SafeMinutes is a tool — it does not verify the legal validity of your resolutions or the accuracy of your director records.`,
  },
  {
    title: 'Acceptable use',
    body: `You may not use SafeMinutes to conduct fraudulent governance — for example, recording resolutions that were never passed, fabricating attendance records, or generating minutes for meetings that did not occur.

You may not attempt to circumvent the security or access controls of the platform, probe or scan the platform for vulnerabilities, or interfere with the service for other users.

You may not use automated scripts to interact with the platform in a way that creates disproportionate load. Our API is available for legitimate integration purposes — contact us if you need API access.`,
  },
  {
    title: 'Statutory records',
    body: `SafeMinutes generates documents designed to meet the requirements of the Companies Act 2013 and ICSI Secretarial Standard SS-1. However, we make no warranty that documents generated by the platform will be accepted by any regulator, court, bank, or third party in any specific situation.

You are responsible for reviewing all generated documents — minutes, attendance registers, certified copies — for accuracy before they are signed or relied upon. SafeMinutes automates the formatting and record-keeping, not the legal judgment.

If you identify an error in a document generated by SafeMinutes, you are responsible for correcting it before the document is signed and locked. Once signed and locked, documents are preserved as-is per the statutory record.`,
  },
  {
    title: 'Service availability',
    body: `We aim to maintain SafeMinutes availability at or above 99.5% in any calendar month, excluding scheduled maintenance windows which we will communicate at least 24 hours in advance.

During the early access beta period, the service is provided as-is. We may update, modify, or occasionally take the service offline without prior notice for maintenance or improvements. We will endeavour to provide advance notice of planned downtime.

We are not liable for any loss arising from service unavailability. For critical governance events (e.g., a board meeting scheduled for a specific time), we recommend having a fallback process in place.`,
  },
  {
    title: 'Pricing',
    body: `SafeMinutes is currently free to use during the early access beta period. We will provide at least 30 days notice before introducing paid plans or restricting access to features that are currently free.

When paid plans are introduced, you will have the option to continue on a free tier (with feature limitations to be defined), upgrade to a paid plan, or export your data and close your account. We will never delete your data without giving you an opportunity to export it first.`,
  },
  {
    title: 'Termination',
    body: `You may close your account at any time by contacting hello@safeminutes.com. We will delete your personal data within 30 days. Governance records associated with your company workspaces are retained for the statutory period described in our Privacy Policy.

We may suspend or terminate your account if you breach these terms, engage in fraudulent activity, or create legal, regulatory, or reputational risk for Passhai Technologies. We will notify you of termination unless it is necessary to act immediately for security reasons.`,
  },
  {
    title: 'Limitation of liability',
    body: `To the extent permitted by applicable law, Passhai Technologies is not liable for any indirect, incidental, special, or consequential damages arising from your use of SafeMinutes, including but not limited to: loss of revenue, regulatory penalties, or third-party claims arising from governance records generated by the platform.

Our aggregate liability for direct damages in any calendar year is limited to the amounts you paid us in that year. During the free beta period, our aggregate liability is limited to ₹1,000.

Nothing in these terms limits our liability for fraud, gross negligence, or claims that cannot be excluded under applicable Indian law.`,
  },
  {
    title: 'Governing law',
    body: `These terms are governed by the laws of India. Any disputes arising from these terms or your use of SafeMinutes will be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, India.

If you have a dispute with us, please contact hello@safeminutes.com before initiating legal proceedings. We will make a genuine effort to resolve disputes directly.`,
  },
  {
    title: 'Changes to these terms',
    body: `We may update these terms from time to time. Material changes will be notified by email at least 14 days before they take effect. The date at the top of this page reflects the last update. Continued use of SafeMinutes after the effective date of updated terms constitutes acceptance.

If you do not agree with a material change, you may close your account before the change takes effect.`,
  },
  {
    title: 'Contact',
    body: `For questions about these terms, contact us at hello@safeminutes.com.

Passhai Technologies Private Limited
India`,
  },
];

export default function TermsPage() {
  const C = {
    charcoal: '#1C1A18', charcoalBdr: 'rgba(255,255,255,0.07)',
    stone: '#F5F2EE', rule: '#E0DAD2', crimson: '#8B1A1A',
    ink: '#231F1B', inkMid: '#5C5750', inkMute: '#96908A',
  };

  return (
    <div style={{ fontFamily: "'Instrument Sans', system-ui, sans-serif", background: C.stone, color: C.ink, minHeight: '100vh' }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400&family=Instrument+Sans:wght@400;500;600&family=Crimson+Pro:ital,wght@0,300;0,400;1,300;1,400&display=swap');*{box-sizing:border-box}`}</style>

      {/* Header */}
      <header style={{ background: C.charcoal, borderBottom: `1px solid ${C.charcoalBdr}`, padding: '0 52px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '58px', maxWidth: '820px', margin: '0 auto' }}>
          <a href="/" style={{ display: 'flex', alignItems: 'center', gap: '10px', textDecoration: 'none' }}>
            <CastleLogo />
            <div style={{ width: 1, height: 18, background: 'rgba(255,255,255,0.15)', margin: '0 2px' }} />
            <span style={{ fontSize: '13px', fontWeight: 600, color: '#fff', letterSpacing: '0.09em', textTransform: 'uppercase' }}>SafeMinutes</span>
          </a>
          <a href="/" style={{ fontSize: '12px', color: 'rgba(255,255,255,0.38)', textDecoration: 'none' }}>← Back to home</a>
        </div>
      </header>

      {/* Content */}
      <div style={{ maxWidth: '680px', margin: '0 auto', padding: '64px 48px 96px' }}>

        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', fontSize: '10px', fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: C.crimson, marginBottom: '14px' }}>
          <span style={{ width: '16px', height: '2px', background: C.crimson, display: 'inline-block' }} />
          Legal
        </div>

        <h1 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: '2.2rem', fontWeight: 600, lineHeight: 1.12, letterSpacing: '-0.02em', color: C.ink, marginBottom: '10px' }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: '15px', color: C.inkMute, marginBottom: '48px' }}>
          Last updated: March 2026 &middot; Passhai Technologies Private Limited
        </p>

        <p style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: '17px', lineHeight: 1.75, color: C.inkMid, marginBottom: '48px', paddingBottom: '32px', borderBottom: `1px solid ${C.rule}` }}>
          These terms govern your use of SafeMinutes. We have written them to be clear and direct. The short version: be honest, respect other users, and do not use the platform for fraudulent governance. The detailed version follows below.
        </p>

        {sections.map((s, i) => (
          <div key={i} style={{ marginBottom: '40px', paddingBottom: '40px', borderBottom: i < sections.length - 1 ? `1px solid ${C.rule}` : 'none' }}>
            <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: '1.25rem', fontWeight: 600, color: C.ink, marginBottom: '14px', lineHeight: 1.2 }}>
              {s.title}
            </h2>
            {s.body.split('\n\n').map((para, j) => (
              <p key={j} style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: '16px', lineHeight: 1.75, color: C.inkMid, margin: '0 0 14px' }}>
                {para}
              </p>
            ))}
          </div>
        ))}

      </div>

      {/* Footer */}
      <footer style={{ background: C.charcoal, borderTop: `1px solid ${C.charcoalBdr}`, padding: '24px 52px' }}>
        <div style={{ maxWidth: '820px', margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.25)' }}>© 2026 Passhai Technologies Private Limited</span>
          <div style={{ display: 'flex', gap: '20px' }}>
            {[['Beta Terms', '/beta-terms'], ['Privacy', '/privacy'], ['Terms', '/terms']].map(([label, href]) => (
              <a key={label} href={href} style={{ fontSize: '12px', color: 'rgba(255,255,255,0.3)', textDecoration: 'none' }}>{label}</a>
            ))}
          </div>
        </div>
      </footer>
    </div>
  );
}
