import { IsString, IsOptional, IsBoolean, IsIn } from 'class-validator';

// One of the three evidence paths must be provided.
// Path A (vault/meeting doc) is already linked via vaultDocId/meetingDocId on the resolution.
// This DTO covers Path B (external URL) and Path C (physical presence).

export const EXTERNAL_PLATFORMS = ['MCA21', 'Google Drive', 'Dropbox', 'OneDrive', 'Other'] as const;
export type ExternalPlatform = typeof EXTERNAL_PLATFORMS[number];

export class SetEvidenceDto {
  // Path B — external platform
  @IsOptional()
  @IsString()
  externalDocUrl?: string;

  @IsOptional()
  @IsIn(EXTERNAL_PLATFORMS)
  externalDocPlatform?: ExternalPlatform;

  // Path C — physical presence at deemed venue
  @IsOptional()
  @IsBoolean()
  physicallyPresent?: boolean;

  @IsOptional()
  @IsString()
  physicalEvidence?: string; // auto-generated by frontend: "Physically present at [venue] — [date]"
}
